language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sandbox-reactjs' ]; then cd .. && eval "mv $currentfolder sandbox-reactjs" && cd sandbox-reactjs; fi
